paas:
  rootDomain: paas.local.maxine4j.com
  auth:
    jwtSecret: test-jwt-secret
    sessionLifetimeSeconds: 604800 # 1 week
    oauth2Provider:
      type: github
      clientId: ...
      clientSecret: ...
    authorizedUserIds:
      - 'maxine4j'
    adminUserIds:
      - 'maxine4j'
    deployTokens:
      - name: deploy-pipe
        token: deploy:test-token
        authorizedServices:
          - test-service
  tls:
    envType: staging
    dnsChallengeProvider:
      type: digitalocean
      domain: 'maxine4j.com'
      accessToken: ...
