paas:
  rootDomain: '...'
  
  auth:
    jwtSecret: ...
    sessionLifetimeSeconds: 604800 # 1 week
    oauth2Provider:
      type: github
      clientId: '...'
      clientSecret: '...'
    authorizedUserIds:
      - '...'
    adminUserIds:
      - '...'
    deployTokens:
      - name: deploy-pipe
        token: deploy:local
        authorizedServices:
          - test-service

  tls:
    envType: staging
    dnsChallengeProvider:
      type: digitalocean
      domain: '...'
      accessToken: '...'
